version: '3.8'

services:
  capcut-api:
    build: .
    ports:
      - "9001:9001"
    volumes:
      - ./config.json:/app/config.json
      - ./drafts:/app/drafts
      - ./media:/app/media
    environment:
      - PYTHONPATH=/app
      - DEBUG=0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：使用nginx作为反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - capcut-api
    restart: unless-stopped
    profiles:
      - with-nginx